version: '3'
services:
  php:
    build:
      context: .
      args:
        - PROJECT_DIR_ARG=/usr/share/nginx/public
    container_name: ypr-permissions-reborn-php
    user: ${PHPUID}
    volumes:
      - ./project:/usr/share/nginx/public
  nginx:
    image: nginx:1.13.9-alpine
    container_name: ypr-permissions-reborn-nginx
    depends_on:
      - php
    volumes:
      - ./project:/usr/share/nginx/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8889:80 # http://127.0.0.1:8889/